- name: Task1 integrating the Docker with Ansible
  hosts: remote_ip
  tasks:


#Creating a yum repository for docker
     - name: Create Docker Repo
       yum_repository:
          name: docker_repo
          description: Docker Repo
          baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
          gpgcheck: no
     - debug:
          msg: "sucessfully comfigured yum for the Docker"


#installing the docker-ce ( client version )
     - name: install docker
       package:
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present
     - debug: 
          msg: "docker is sucessfully installed"

#start the docker service yto use it
     - name: start the docker
       service:
          name: "docker"
          state: started
          enabled: yes
     - debug:
          msg: "docker service started sucessfully"

#install the docker SDK for python3
     - name: install docker sdk
       command: pip3 install docker
     - debug: 
          msg: "sucessfully installation of docker SDK"

#pull the docker image from docker repository
     - name: pull docker image
       docker_image:
          name: httpd
          source: pull

#create the file where we copy our code to test the httpd server
     - name: create a folder
       file:
          path: "/root/ansiblecode/mycode"
          state: directory

#copy the code from our local sytem to remote system
     - name: copy the code 
       copy:
          src: "/root/ansile-code/task/home.html"
          dest: "/root/ansiblecode/mycode/"
     - name: copy image for code
       copy: 
          src: "/root/ansile-code/task/ansible-container.png"
          dest: "/root/ansiblecode/mycode/"

#launch the container & expose the container
     - name: launch docker container
       docker_container:
          name: httpd-webserver
          image: httpd
          state: started
          exposed_ports: 
            - "80"
          ports:
            - "8585:80"
          volumes:
            - /root/ansiblecode/mycode/:/usr/local/apache2/htdocs/
